"""Generates the icon set.

    python3 tools/icons/gen.py                       # everything: icons/, icons/dark/, src/generated.rs
    python3 tools/icons/gen.py --only sketch --out DIR   # one module's SVGs into DIR (and DIR/dark)

Each module in MODULES registers icons with @icon from common.py. The full run validates every
icon (unique names, palette colours allowed for its kind, well-formed XML) before writing.
"""
import argparse, importlib, os, re, subprocess, sys, tempfile
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import common  # noqa: E402

# Toolbar order: modules in this order, icons in each module in definition order.
MODULES = ["part", "sheet_metal", "assembly", "sketch", "glyphs", "ui_a", "ui_b"]
RUST_KIND = {"solid": "Solid", "sketch": "Sketch", "glyph": "Glyph", "line": "Line"}

# Solid and sketch icons are drawn on the shared 24-unit grid but rarely fill it, which makes them
# hard to read at toolbar size. The fitting pass zooms each one's view box to its ink: a square
# around the ink plus FIT_MARGIN on every side, never zoomed in more than MAX_ZOOM. Line and glyph
# icons keep the standard UI padding.
FIT_KINDS = {"solid", "sketch"}
FIT_MARGIN = 1.0
MAX_ZOOM = 1.5


def render(entry):
    body = entry["fn"]()
    if isinstance(body, (list, tuple)):
        body = "\n  ".join(b for b in body if b)
    stroke, _ = common.KINDS[entry["kind"]]
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" '
            f'fill="none" stroke="{common.INK}" stroke-width="{stroke}" stroke-linejoin="round" '
            f'stroke-linecap="round">\n  {body}\n</svg>\n')


def validate(entry, svg):
    name, kind = entry["name"], entry["kind"]
    problems = []
    if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", name):
        problems.append("name must be kebab-case")
    try:
        ET.fromstring(svg)
    except ET.ParseError as e:
        problems.append(f"bad XML: {e}")
    allowed = common.KINDS[kind][1]
    for colour in set(re.findall(r"#[0-9a-fA-F]{6}\b", svg)):
        if colour not in allowed:
            problems.append(f"colour {colour} not allowed for kind {kind}")
    if re.search(r"\bid=", svg):
        problems.append("ids are not allowed (they clash when icons are inlined); avoid clipPath/defs")
    return [f"{entry['module']}.{name}: {p}" for p in problems]


def dark(svg):
    # One pass, so a dark colour equal to a later light colour is not replaced again.
    return re.sub(r"#[0-9a-f]{6}\b", lambda m: common.DARK_PALETTE.get(m.group(0), m.group(0)), svg)


def ink_bounds(entries):
    """{name: (x0, y0, x1, y1)} of the rendered ink, via examples/bbox.rs."""
    with tempfile.TemporaryDirectory() as tmp:
        files = []
        for e in entries:
            path = os.path.join(tmp, f"{e['name']}.svg")
            with open(path, "w") as fh:
                fh.write(e["svg"])
            files.append(path)
        run = subprocess.run(["cargo", "run", "--release", "-q", "--example", "bbox", "--", *files],
                             cwd=ROOT, capture_output=True, text=True)
        if run.returncode != 0:
            sys.exit(f"bbox failed:\n{run.stderr}")
    out = {}
    for line in run.stdout.splitlines():
        name, *nums = line.split()
        out[name] = tuple(map(float, nums))
    return out


def fit(entries):
    """Zooms each fitted icon's view box to its ink."""
    fitted = [e for e in entries if e["kind"] in FIT_KINDS]
    if not fitted:
        return
    bounds = ink_bounds(fitted)
    for e in fitted:
        x0, y0, x1, y1 = bounds[e["name"]]
        side = min(24.0, max(max(x1 - x0, y1 - y0) + 2 * FIT_MARGIN, 24.0 / MAX_ZOOM))
        cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
        vb = f"{common.f(cx - side / 2)} {common.f(cy - side / 2)} {common.f(side)} {common.f(side)}"
        e["svg"] = e["svg"].replace('viewBox="0 0 24 24"', f'viewBox="{vb}"', 1)


def write(out, entries):
    os.makedirs(os.path.join(out, "dark"), exist_ok=True)
    for e in entries:
        with open(os.path.join(out, f"{e['name']}.svg"), "w") as fh:
            fh.write(e["svg"])
        with open(os.path.join(out, "dark", f"{e['name']}.svg"), "w") as fh:
            fh.write(dark(e["svg"]))


def rust(entries):
    lines = ["// Generated by tools/icons/gen.py. Do not edit.", "", "icons! {"]
    for e in entries:
        konst = e["name"].upper().replace("-", "_")
        title = e["title"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {konst} => ("{e["name"]}", {RUST_KIND[e["kind"]]}, "{title}"),')
    lines.append("}")
    return "\n".join(lines) + "\n"


def check_palette():
    """The palette in common.py must match Palette::LIGHT and Palette::DARK in src/lib.rs."""
    lib = open(os.path.join(ROOT, "src", "lib.rs")).read()
    slots = ["ink", "top", "soft", "mid", "shade", "accent"]
    light = [common.INK, common.TOP, common.SOFT, common.MID, common.SHADE, common.ACCENT]
    problems = []
    for name, want in [("LIGHT", light), ("DARK", [common.DARK_PALETTE[c] for c in light])]:
        body = re.search(rf"pub const {name}: Palette = Palette \{{(.*?)\}};", lib, re.S).group(1)
        got = {k: "#" + r + g + b for k, r, g, b in re.findall(r"(\w+): Rgb\(0x(\w\w), 0x(\w\w), 0x(\w\w)\)", body)}
        for slot, colour in zip(slots, want):
            if got.get(slot) != colour:
                problems.append(f"Palette::{name}.{slot} is {got.get(slot)} in src/lib.rs but {colour} in common.py")
    return problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="generate a single module")
    ap.add_argument("--out", help="output directory (default: icons/)")
    args = ap.parse_args()

    modules = [args.only] if args.only else MODULES
    for m in modules:
        importlib.import_module(m)

    entries, problems, seen = [], check_palette(), {}
    for e in common.REGISTRY:
        if e["name"] in seen:
            problems.append(f"{e['module']}.{e['name']}: duplicate of {seen[e['name']]}.{e['name']}")
            continue
        seen[e["name"]] = e["module"]
        try:
            e["svg"] = render(e)
        except Exception as ex:  # report every broken icon, not just the first
            problems.append(f"{e['module']}.{e['name']}: {type(ex).__name__}: {ex}")
            continue
        problems += validate(e, e["svg"])
        entries.append(e)
    if problems:
        print("\n".join(problems), file=sys.stderr)
        sys.exit(1)

    fit(entries)
    out = args.out or os.path.join(ROOT, "icons")
    if not args.only:
        # A full run owns icons/: remove files for icons that no longer exist.
        for sub in ("", "dark"):
            d = os.path.join(out, sub)
            if os.path.isdir(d):
                for fn in os.listdir(d):
                    if fn.endswith(".svg") and fn[:-4] not in seen:
                        os.remove(os.path.join(d, fn))
    write(out, entries)
    if not args.only and not args.out:
        with open(os.path.join(ROOT, "src", "generated.rs"), "w") as fh:
            fh.write(rust(entries))
    print(f"{len(entries)} icons -> {out}")


if __name__ == "__main__":
    main()
